### ISSUE TITLE
mewhenissue

### ISSUE THREAD

**Issue by rohanthmarem** [moochezz/mewhen#1]
this is an ongoing issue pls fix asap

**Comment by moochezz** [comment]
fixing rn!!!!

**Comment by moochezz** [comment]
i have found the root cause, it was that i had 0 braincells!!!

**Comment by moochezz** [comment]
this issue cant be fixed sorry

**Comment by moochezz** [comment]
this issue cant be fixed sorry

**Comment by rohanthmarem** [comment]
sadge
